[[headers]]
  for = "/*"
  [headers.values]
    access-control-allow-origin = "http://localhost:3006"
    access-control-allow-credentials = "true"
    access-control-allow-headers = "Content-Type, Authorization"
